version: "2"
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
    - "27017:27017"

  eureka:
    image: eureka
    container_name: eureka
    ports:
      - "8761:8761"

  config-server:
    image: config-server
    container_name: config-server
    ports:
    - "8888:8888"

  admin-service:
    image: admin-service
    container_name: admin-service
    restart: on-failure
    environment:
      - PROFILE=docker
      - CONFIG_URI=http://config-server:8888
    ports:
    - "8001:8001"
    depends_on:
      - eureka
      - mongo

  expense-service:
    image: expense-service
    container_name: expense-service
    restart: on-failure
    environment:
    - PROFILE=docker
    - CONFIG_URI=http://config-server:8888
    ports:
    - "8011:8011"
    depends_on:
    - eureka
    - mongo
    - admin-service
