spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: admin-servicre
          uri: lb://admin-service
          predicates:
          - Path=/admin-service/**
        - id: expene-service
          uri: lb://expense-service
          predicates:
          - Path=/expense-service/**

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG