spring:
  application:
    name: admin-service
  cloud:
    config:
      uri: http://locakhost:8888

server:
  port: 8001
  servlet:
    context-path: /${spring.application.name}/

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]
        exclude: ["env", "beans"]
