spring:
  application:
    name: admin-service
  cloud:
    config:
      uri: http://locakhost:8888
#  cache:
#    jcache:
#      config: ehcache.xml

server:
  port: 8001
  servlet:
    context-path: /${spring.application.name}/
  error:
    include-stacktrace: never


management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: ["health", "info", "refresh"]
        exclude: ["env", "beans"]
