name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package -DskipTests=true --file pom.xml
    - name: Build the Eureka Docker image
      run: docker build --file eureka/Dockerfile --tag eureka:$(date +%s) eureka
    - name: Build the ConfigServer Docker image
      run: docker build --file config-server/Dockerfile --tag config-server:$(date +%s) eureka
    - name: Build the AdminService Docker image
      run: docker build --file admin-service/Dockerfile --tag admin-service:$(date +%s) eureka
    - name: Build the ExpenseService Docker image
      run: docker build --file expense-service/Dockerfile --tag expense-service:$(date +%s) eureka
